#!/usr/bin/env python3
"""Regenerate nifty_heatmap_core/company_names.py from NSE's equity master list.

    curl -sA "Mozilla/5.0" -o EQUITY_L.csv https://nsearchives.nseindia.com/content/equities/EQUITY_L.csv
    python3 scripts/build_company_names.py EQUITY_L.csv

The table is checked in rather than fetched at run time, so the per-minute
data job never depends on reaching NSE. Re-run when the universe gains names
(the build prints any symbol it could not find - add those to OVERRIDES).
"""
import csv, os, re, sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import nifty_heatmap_core as core

# Symbols missing from NSE's list (renamed/merged after the universe was set).
OVERRIDES = {
    "JBCHEPHARM": "JB Chemicals & Pharmaceuticals",
    # NSE lists these in capitals; tiles read better in normal case.
    # (360ONE is left as "360 ONE WAM" - that is the company's own styling.)
    "ETERNAL": "Eternal",
    "FORCEMOT": "Force Motors",
    "GMRAIRPORT": "GMR Airports",
    "JINDALSTEL": "Jindal Steel",
    "SAGILITY": "Sagility",
    "SHREECEM": "Shree Cement",
    "TATACONSUM": "Tata Consumer Products",
}


def tidy(name):
    """'Infosys Limited' -> 'Infosys'; keeps the registered wording otherwise."""
    name = re.sub(r"\s+", " ", name).strip()
    name = re.sub(r"\s*(Limited|Ltd\.?)$", "", name, flags=re.I).strip()
    return name


src = sys.argv[1]
master = {r["SYMBOL"].strip(): r["NAME OF COMPANY"].strip() for r in csv.DictReader(open(src))}
symbols = sorted({t.replace(".NS", "") for t in list(core.FNO_ALL) + list(core.NIFTY50)})
names, missing = {}, []
for s in symbols:
    if s in OVERRIDES:
        names[s] = OVERRIDES[s]
    elif s in master:
        names[s] = tidy(master[s])
    else:
        missing.append(s)

out = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "nifty_heatmap_core", "company_names.py")
with open(out, "w") as f:
    f.write('"""NSE symbol -> company name, for display under the ticker.\n\n'
            'GENERATED by scripts/build_company_names.py from NSE\'s EQUITY_L.csv -\n'
            'edit OVERRIDES there and re-run, do not edit this file by hand."""\n\n'
            "COMPANY_NAMES = {\n")
    for s in sorted(names):
        f.write(f"    {s!r}: {names[s]!r},\n")
    f.write("}\n")
print(f"{len(names)} names written to {out}")
if missing:
    print("NOT FOUND (add to OVERRIDES):", ", ".join(missing))
    sys.exit(1)
